server {
    listen 80;
    server_name hzortech.com www.hzortech.com;
    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name hzortech.com www.hzortech.com;

    # Let’s Encrypt SSL paths (created on EC2)
    ssl_certificate /etc/letsencrypt/live/hzortech.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hzortech.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Proxy Django Gunicorn
    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serve static files
    location /static/ {
        alias /app/staticfiles/;
    }

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
}